--- #YAML:1.0
name:               Locale-CA
version:            0.01
abstract:           two letter codes for province identification in Canada and vice versa
author:
    - Nigel Horne <njh@bandsman.co.uk>
license:            GPL
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Data::Section::Simple:  0
    Test::More:           0.82
    Test::NoWarnings:     0
    Test::Requires:       0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
